name: autosign
on: 
    push:
        branches:
            - master
        schedule:
            - cron: "20 16 * * *"
jobs:
    start_sign:
        name: start daily sign
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              use: actions/checkout@master
            - name: setup python
              use: actions/setup-python@v2
              with:
                python-version: '3.x'
                architecture: 'x64'
            - name: start psnine signup
              env:
                USR: ${{ secrets.USR }}
                PASS: ${{ secrets.PASS }}
              run: |
                echo "Install Dependencies"
                pip install requests
                echo "Start sign"
                python psnineQidau.py